var data = [
    // offensive
    [
        {
            index: 1,
            name: "Deadliness",
            ranks: 3,
            desc: "Grants 0.66/1.33/2% critical strike chance.",
            rankInfo: [],
        },
        {
            index: 2,
			
            name: "Cripple",
            ranks: 1,
            desc: "Improves your Exhaust spell to also reduce the target's armor and magic resistance by 10 for the duration, and increases its duration by 0.5 seconds.",
            rankInfo: [],
        },
        {
            index: 3,
            name: "Plentful Bounty",
            ranks: 1,
            desc: "Improves your Smite spell to grant bonus Gold 5 when used, and reduces its cooldown by 5 seconds.",
            rankInfo: [],
        },
        {
            index: 4,
            name: "Archmage's Savvy",
            ranks: 3,
            desc: "Grants 0.2/0.4/0.6 ability power per level.",
            rankInfo: [],
        },
        {
            index: 6,
            name: "Sorcery",
            ranks: 4,
            desc: "Grans 0.75/1.5/2.25/3% cooldown reduction",
            rankInfo: [],
        },
        {
            index: 7,
            name: "Alacrity",
            ranks: 4,
            desc: "Grants 1/2/3/4% attack speed.",
            rankInfo: [],
        },
        {
            index: 9,
            name: "Burning Embers",
            ranks: 1,
            desc: "While your Ignite Ignite spell is on cooldown, grants 10 ability power.",
            rankInfo: [],
        },
        {
            index: 10,
            name: "Archaic Knowledge",
            ranks: 1,
            desc: "Grants 15% magic penetration.",
            rankInfo: [],
        },
        {
            index: 11,
            name: "Sunder",
            ranks: 3,
            desc: "Grants 2 / 4 / 6 armor penetration.",
            rankInfo: [],
        },
        {
            index: 12,
            name: "Offensive Mastery",
            ranks: 2,
            desc: "Basic attacks and single target spells deal 2 / 4 bonus damage to minions and monsters.",
            rankInfo: [],
            parent: 5,
        },
        {
            index: 14,
            name: "Brute Force",
            ranks: 3,
            desc: "Grants 1 / 2 / 3 attack damage.",
            rankInfo: [],
            rankInfo2: [],
        },
        {
            index: 15,
            name: "Demolisher",
            ranks: 1,
            desc: "Reduces Promote's cooldown by 15 seconds, increases damage dealt to turrets by 15 while Promote is off cooldown, and increases the Promoted unit's armor by 20.",
            rankInfo: [],
        },
        {
            index: 18,
            name: "Lethality",
            ranks: 2,
            desc: "Increases critical strike damage by 2.5 / 5% for ranged champions and by 5 / 10% for melee champions.",
            rankInfo: [],
        },
        {
            index: 19,
            name: "Improved Rally",
            ranks: 1,
            desc: "Improves your Rally Rally to also grant 20 - 70 ability power and increase its duration by 5 seconds.",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Havoc",
            ranks: 1,
            desc: "Increase your physical damage and magic damage by 4% each",
            rankInfo: [],
        },
    ],
// defensive
    [
        {
            index: 1,
            name: "Mender's Faith",
            ranks: 1,
            desc: "Reduces the cooldown of your Heal spell by 30 seconds.",
            rankInfo: [],
        },
        {
            index: 2,
            name: "Resistance",
            ranks: 3,
            desc: "Grants 2/ 4/ 6 magic resistance.",
            rankInfo: [2, 4, 6],
        },
        {
            index: 3,
            name: "Preservation",
            ranks: 1,
            desc: "Grants 400 bonus health for 120 seconds after casting Revive while also reducing its cooldown by 30 seconds.",
            rankInfo: [],
        },
        {
            index: 4,
            name: "Hardiness",
            ranks: 3,
            desc: "Grants 2/ 3.5/ 5 armor",
            rankInfo: [2, 3.5, 5],
        },
        {
            index: 6,
            name: "Strength of Spirit",
            ranks: 3,
            desc: "Increases health regeneration per 5 seconds by 0.33/0.66/1% maximum mana",
            rankInfo: [0.33, 0.66, 1  ],
            parent: 1,
        },
        {
            index: 7,
            name: "Evasion",
            ranks: 4,
            desc: "Grants 0.5/1/1.5/2% dodge chance.",
            rankInfo: [0.5, 1, 1.5, 2],
        },
        {
            index: 10,
            name: "Defensive Mastery",
            ranks: 2,
            desc: "Reduces by 1/2 damage taken from minions and monsters.",
            rankInfo: [1, 2],
        },
        {
            index: 11,
            name: "Nimbleness",
            ranks: 1,
            desc: "Grants 10% bonus movement speed for 5 seconds after dodging an attack",
            rankInfo: [],
            parent: 5
        },
        {
            index: 12,
            name: "Harden Skin",
            ranks: 3,
            desc: "Blocks 1/ 1.5/2 physical damage from all sources.",
            rankInfo: [1, 1.5, 2],
            parent: 3
        },
        {
            index: 14,
            name: "Veteran's Scars",
            ranks: 4,
            desc: "Grants 12/ 24/ 36/ 48 health",
            rankInfo: [12, 24, 36 ,48],
        },
        {
            index: 15,
            name: "Willpower",
            ranks: 1,
            desc: "Reduces the cooldown of Cleanse by 20 seconds.",
            rankInfo: [],
        },
        {
            index: 18,
            name: "Ardor",
            ranks: 3,
            desc: "Grants 1.33/2.66/4% ability power and 1.33/2.66/4% bonus attack speed",
            rankInfo: [1.33, 2.66, 4],
        },
        {
            index: 19,
            name: "Reinforce",
            ranks: 1,
            desc: "Your Fortify and Garrison spells causes allied turrets to deal 50% splash damage",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Tenacity",
            ranks: 1,
            desc: "Reduces all damage dealt to your champion by 4%",
            rankInfo: [],
        },
    ],
      // Misc
    [
        {
            index: 1,
            name: "Spatial Accuracy",
            ranks: 1,
            desc: "Reduces the delay on your Teleport spell by 0.5 seconds, and reduces its cooldown by 5 seconds. Reduce Promote's cooldown by 30 seconds.",
            rankInfo: [],
        },
        {
            index: 2,
            name: "Good Hands",
            ranks: 3,
            desc: "Reduces time spent dead by 3.33/ 6.66/ 10%",
            rankInfo: [3.33, 6.66, 10],
        },
        {
            index: 3,
            name: "Perseverance",
            ranks: 3,
            desc: "Increases your total health and mana regeneration by 2/ 3/ 4% each.",
            rankInfo: [2, 3, 4],
        },
        {
            index: 4,
            name: "Haste",
            ranks: 1,
            desc: "Increases the movement speed of Ghost by 6% and its duration by 15 seconds",
            rankInfo: [],
        },
        {
            index: 6,
            name: "Awareness",
            ranks: 3,
            desc: "Increases champion experience gained by 1.25/ 2.5/ 3.75/ 5%",
            rankInfo: [1.25, 2.5, 3.75, 5],
        },
        {
            index: 7,
            name: "Expanded Mind",
            ranks: 4,
            desc: "Increases maximum mana by 1.25/ 2.5/ 3.75/ 5%",
            rankInfo: [1.25, 2.5, 3.75, 5],
        },
        {
            index: 9,
            name: "Greed",
            ranks: 1,
            desc: "Grants +1 Gold per 10 seconds",
            rankInfo: [],
        },
        {
            index: 10,
            name: "Meditation",
            ranks: 3,
            desc: "Grants 1/ 2/ 3 mana regeneration per 5 seconds",
            rankInfo: [1, 2, 3],
        },
        {
            index: 11,
            name: "Utility Mastery",
            ranks: 2,
            desc: "Increases the duration of shrines, relics, quests, and neutral monster buffs by 15/ 30%.",
            rankInfo: [15, 30],
        },
        {
            index: 12,
            name: "Insight",
            ranks: 1,
            desc: "Clarity will now grant the same amount of mana to allies as your champion receives.",
            rankInfo: [],
        },
        {
            index: 15,
            name: "Quickness",
            ranks: 3,
            desc: "Grants 1/ 2/ 3% movement speed.",
            rankInfo: [1, 2, 3],
        },
        {
            index: 16,
            name: "Blink of an Eye",
            ranks: 1,
            desc: "Reduces the cooldown of Flash by 15 seconds.",
            rankInfo: [],
        },
        {
            index: 18,
            name: "Intelligence",
            ranks: 3,
            desc: "Grants 2/ 4/ 6% cooldown reduction",
            rankInfo: [2, 4, 6],
        },
        {
            index: 19,
            name: "Mystical Vision",
            ranks: 1,
            desc: "Increases the duration of Clairovayance by 4 seconds, and reduces its cooldown by 5 seconds",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Presence of Master",
            ranks: 1,
            desc: "Reduces the recharge time of summoner spells by 15%",
            rankInfo: [],
        },
    ]
];
